# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

dev:
  link_to:
    association:        http://association-up2green.smartit.fr/
    search:             http://up2green.smartit.fr/
    reforestation:      http://reforestation-up2green.smartit.fr/
  
all:
  sfJqueryTree:
    withContextMenu : false
  cultures:
    enabled:
      fr: Français
      en: English
  ckeditor:
    basePath:         "/js/ckeditor/"
  ckfinder:
    active:           true
    basePath:         '/js/ckfinder/'
  link_to:
    association:      http://association.up2green.com/
    search:           http://www.up2green.com/
    reforestation:    http://reforestation.up2green.com/

