partenaire:
  class: sfDoctrineRouteCollection
  options:
    model:                Partenaire
    module:               partenaire
    prefix_path:          /partenaire
    column:               id
    with_wildcard_routes: true

generate_coupons:
  url: /partenaire/generateCoupons/*
  param: { module: partenaire, action: generateCoupons }
  
user_forgot_password:
  url:   /forgotpwd
  param: { module: user, action: forgotPassword }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

category_category:
  class: sfDoctrineRouteCollection
  options:
    model:               category
    module:              category
    prefix_path:         category
    column:              id
    with_wildcard_routes: true

category:
  class: sfDoctrineRouteCollection
  options:
    model:               category
    module:              category
    prefix_path:         category
    column:              id
    with_wildcard_routes: true

coupon:
  class: sfDoctrineRouteCollection
  options:
    model:                couponGen
    module:               coupon
    prefix_path:          /coupon
    column:               id
    with_wildcard_routes: true

organisme:
  class: sfDoctrineRouteCollection
  options:
    model:                organisme
    module:               organisme
    prefix_path:          /organisme
    column:               id
    with_wildcard_routes: true

programme:
  class: sfDoctrineRouteCollection
  options:
    model:                programme
    module:               programme
    prefix_path:          /programme
    column:               id
    with_wildcard_routes: true
    
newsletter:
  class: sfDoctrineRouteCollection
  options:
    model:                Newsletter
    module:               newsletter
    prefix_path:          /newsletter
    column:               id
    with_wildcard_routes: true

article:
  class: sfDoctrineRouteCollection
  options:
    model:                Article
    module:               article
    prefix_path:          /article
    column:               id
    with_wildcard_routes: true

lien:
  class: sfDoctrineRouteCollection
  options:
    model:                Lien
    module:               lien
    prefix_path:          /lien
    column:               id
    with_wildcard_routes: true

# default
homepage:
  url:   /
  param: { module: organisme, action: index }

# generic rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
