generator:
  class: sfDoctrineGenerator
  param:
    model_class:           logCoupon
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          log_coupon
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        object_actions: []
        actions: []
      filter:  ~
      form:    ~
