generator:
  class: sfDoctrineGenerator
  param:
    model_class:           coupon
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          coupon
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des coupons
      filter:  ~
      form:    ~
      edit:
        title: Modifier un coupon
      new:
        title: Nouveau coupon
