generator:
  class: sfDoctrineGenerator
  param:
    model_class:           newsletter
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          newsletter
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=title, is_forced, sent_at]
        object_actions:
          _edit:        ~
          _delete:      ~
          sendToOne:        { label: Send to one, action: sendToOne }
          sendToAll:        { label: Send to all, action: sendToAll }
          sendToAllForced:  { label: Send to all (without check), action: sendToAllForced }
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
