generator:
  class: sfDoctrineGenerator
  param:
    model_class:           newsletter
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          newsletter
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=title, is_forced, sent_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
