showSuccess:
  stylesheets:
    - "jquery.galleryview-3.0.css?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "jquery.easing.1.3.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.timers-1.2.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.galleryview-3.0.js?v=<?php echo sfConfig::get('app_media_version') ?>"
  layout: layout