all:
  layout: moteur
  stylesheets:
    - "moteur.css?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "min/jquery.text-overflow.min.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "moteur.js?v=<?php echo sfConfig::get('app_media_version') ?>"
  metas:
    title: "Up2green : Le Moteur de recherche"