# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  metas:
    title: "Up2green : Le Moteur de recherche"
  layout: moteur
  stylesheets:
    - "reset?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "main?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "button?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "module?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "moteur?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "tooltip?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.gritter?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "min/jquery-1.4.4.min?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "min/jquery-ui-1.8.2.custom.min?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "min/jquery.gritter.min?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.scrollTo?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "main?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "moteur?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "min/jquery.text-overflow.min?v=<?php echo sfConfig::get('app_media_version') ?>"
