prod:
  jmsPaymentPlugin:
    paypal:
      username: 'antoine.gerigne_api1.up2green.com'
      signature: 'AFbF3MLf8s8cAfgEC3-ZHq3jtLkAAg5billJSDcrHR0jhWshMoGmx3bP'
      password: 'EH6S97W3Q2W7HTWR'
  yahoo_id: qCd9GP_V34GziYYOdugq_jWiY102W85s.9Hu9pjAkOTa8w1Q7XvgPa2i2jxPl689t9egrleLb1g-
  url_blog: http://association.up2green.com/
  url_moteur: http://www.up2green.com/
  url_plantation: http://reforestation.up2green.com/
  url_admin: http://admin.up2green.com/

dev:
  jmsPaymentPlugin:
    paypal:
      username: 'test_1306521590_biz_api1.up2green.com'
      signature: 'A.ZQCpvrRWwBbYXb9.MR7.zhHtKSA3R02020efHBK07kz.F.4nRihphP'
      password: '1306521599'
  yahoo_id: .Zxf34nV34EVzJToKAQqU49YyS3jqm7E3po9WOgtA0tiFvw6tsZ1l_Wb.EK4U9YhhVlVyf30cWI-
  url_blog: http://association-up2green.smartit.fr/
  url_moteur: http://up2green.smartit.fr/
  url_plantation: http://reforestation-up2green.smartit.fr/
  url_admin: http://admin-up2green.smartit.fr/

all:
  payements:
    enabled:
      - paypal
      - paybox
  max_default_list_item: 10
  media_version: 15
  cultures:
    enabled:
      fr: Français
      en: English
  conversion_tree_co2: 0.1
  prix_credit: 2
  gain_parrain: 0.1
  prix_arbre: 1
  hardcode_tree_number: 8847
  gain_cpc: 0.04
  base_search: 10
  more_search: 10
  max_programme_plantation_list: 10
  google_maps_api:
    keys:
      88.160.179.194: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxTzS27WZts-8OABpbNREg0l7jdhvxS_F5G6BDQGS2k5eFsNty94e0_K2Q
      up2green.smartit.fr: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxRl8TZQpx4J8W_1diLyzFI9z11ZtxQvOxMAOgUQ5et4McN7J3FQK5D3tA
      beta.up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxRkOBGtrsSrBVgrouslRw5t02jcoRQ8kNtmA__lATglfkWBMkTDc4SXOA
      up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxQQ2IcQ8r1Qv5dRlDhwKbdRYDF7HxRuiupUXC_BPbbnWyhecE09zVmWVw
      association.up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxSMxWziwZE0q5SnpdAzKN5C-SSmrxS8dKQfEWEuPSWPs2UKNN22RNPvPg
      reforestation.up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxQlX5wtyYlsmBkElzWwNgT2s-GV5RTN5lj5AWZsN-OSo8hSur9dgaJ8LQ
      www.up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxSbkBb7lgVQWtlidns83ZgJO2fpbxT3-uEu-iZpJj4ZKSDBtjy1G1BJcw
      green.loc: ABQIAAAAsFmetP8aGnqh9wKD7eV4aBSEaGoR3YvicAoDO3yJREyjCR7ArxQYNaiEAo53O2eaWhD_R2QsJh9Cgg
      localhost: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxT2yXp_ZAY8_ufC3CFXhHIE1NvwkxQgsz41bwGYX_jBw9Zh-vi7zT4z-A
      reforestation-up2green.smartit.fr: ABQIAAAA2WG-bF-JJB9XacJsjS1oChRmKgIyMo5pKNttaUp8WCuH0kqYzBTjVkZIFSLyKW6fXpfNJEp4FsNSBw
  url:
    engine_web: http://boss.yahooapis.com/ysearch/web/v1/
    engine_image: http://boss.yahooapis.com/ysearch/images/v1/
    engine_news: http://boss.yahooapis.com/ysearch/news/v1/
    
  blog:
    bloc_articles_max: 3
    bloc_programmes_max: 1
    bloc_partenaires_max: 3
    partenaires_url: http://news.google.fr/news?hl=fr&client=firefox-a&hs=yN1&rls=org.mozilla:fr:official&q=reforestation&um=1&ie=UTF-8&output=rss
    partenaires_open_in_new_window: true

  ddc:
    id: 16945
    hostname: http://yssads.ddc.com/
    path: x1.php
