dev:
  sf_guard_plugin:
    remember_cookie_domain:       .smartit.fr
  jmsPaymentPlugin:
    paypal:
      username: 'test_1306521590_biz_api1.up2green.com'
      signature: 'A.ZQCpvrRWwBbYXb9.MR7.zhHtKSA3R02020efHBK07kz.F.4nRihphP'
      password: '1306521599'
  yahoo_id: .Zxf34nV34EVzJToKAQqU49YyS3jqm7E3po9WOgtA0tiFvw6tsZ1l_Wb.EK4U9YhhVlVyf30cWI-
  url_blog: http://association-up2green.smartit.fr/
  url_moteur: http://up2green.smartit.fr/
  url_plantation: http://reforestation-up2green.smartit.fr/
  url_admin: http://admin-up2green.smartit.fr/

all:
  sf_guard_plugin:
    remember_key_expiration_age:  31536000
    remember_cookie_name:         up2gRememberMe
    remember_cookie_domain:       .up2green.com
    signin_form:                  sfGuardFormSigninCustom
  payments:
    enabled:
      - paypal
  max_default_list_item: 10
  sdf_id: 11
  vedif_id: 8
  validite_coupon: 60
  media_version: 17
  cultures:
    enabled:
      fr: Français
      en: English
  conversion_tree_co2: 0.1
  prix_credit: 2
  gain_parrain: 0.1
  prix_arbre: 1
  hardcode_tree_number: 8847
  gain_cpc: 0.04
  base_search: 10
  more_search: 10
  max_programme_plantation_list: 10
  show_shop_results: false
  
  ckeditor:
    basePath:         "/js/ckeditor/"
  
  ckfinder:
    active:           true
    basePath:         '/js/ckfinder/'
  
  google_maps_api:
    keys:
      localhost: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxT2yXp_ZAY8_ufC3CFXhHIE1NvwkxQgsz41bwGYX_jBw9Zh-vi7zT4z-A
  
  url:
    engine_web: http://yboss.yahooapis.com/ysearch/web
    engine_limitedweb: http://yboss.yahooapis.com/ysearch/limitedweb
    engine_image: http://yboss.yahooapis.com/ysearch/images
    engine_news: http://yboss.yahooapis.com/ysearch/news
    
  blog:
    bloc_articles_max: 3
    bloc_programmes_max: 1
    bloc_partenaires_max: 3
    partenaires_url: http://news.google.fr/news?hl=fr&client=firefox-a&hs=yN1&rls=org.mozilla:fr:official&q=reforestation&um=1&ie=UTF-8&output=rss
    partenaires_open_in_new_window: true

  ddc:
    id: 16945
    hostname: http://yssads.ddc.com/
    path: x1.php

  oauth:
    key: dj0yJmk9b3RGeE84YjBrTldnJmQ9WVdrOVUxSjZXR1ZtTlRJbWNHbzlNVFF4TmpZeU5EVTJNZy0tJnM9Y29uc3VtZXJzZWNyZXQmeD1iYQ--
    secret: 71db0f552d398be0c9e60aab24da4f4bea4418cf
