all:
  base_search: 10
  more_search: 10
  max_programme_plantation_list: 10
  yahoo_id: %20Kj_TvU_V34EbCKKfZ4yPkczw6EL_AFnECTq9EVUyhMyTGgpSf97RhYE6KHWsPQ--
  google_maps_api:
    keys:
      88.160.179.194: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxTzS27WZts-8OABpbNREg0l7jdhvxS_F5G6BDQGS2k5eFsNty94e0_K2Q
      up2green.smartit.fr: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxRl8TZQpx4J8W_1diLyzFI9z11ZtxQvOxMAOgUQ5et4McN7J3FQK5D3tA
      beta.up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxRkOBGtrsSrBVgrouslRw5t02jcoRQ8kNtmA__lATglfkWBMkTDc4SXOA
      up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxQQ2IcQ8r1Qv5dRlDhwKbdRYDF7HxRuiupUXC_BPbbnWyhecE09zVmWVw
      association.up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxSMxWziwZE0q5SnpdAzKN5C-SSmrxS8dKQfEWEuPSWPs2UKNN22RNPvPg
      reforestation.up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxQlX5wtyYlsmBkElzWwNgT2s-GV5RTN5lj5AWZsN-OSo8hSur9dgaJ8LQ
      www.up2green.com: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxSbkBb7lgVQWtlidns83ZgJO2fpbxT3-uEu-iZpJj4ZKSDBtjy1G1BJcw
  url:
    web: http://boss.yahooapis.com/ysearch/web/v1/
    up2green:
      blog: http://association.up2green.com/
      moteur: http://www.up2green.com/
      plantation: http://reforestation.up2green.com/
      admin: http://admin.up2green.com/
  blog:
    bloc_articles_max: 3
    bloc_programmes_max: 1
    bloc_partenaires_max: 3
    partenaires_url: http://news.google.fr/news?hl=fr&client=firefox-a&hs=yN1&rls=org.mozilla:fr:official&q=reforestation&um=1&ie=UTF-8&output=rss
    partenaires_open_in_new_window: true
