# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions
  response:
    class: sfWebResponse
    param:
      send_http_headers: false

dev:
  storage:
    param:
      session_cookie_domain:   .smartit.fr
  mailer:
    param:
      transport:
        class: Swift_SmtpTransport
        param:
          host:       smtp.free.fr
          port:       25

all:
  storage:
    class: plSessionStorage
    param:
      session_name: up2greenSession
      session_cookie_lifetime: 31536000
      session_cookie_domain:   .up2green.com
      db_table:     session
      database:     doctrine
      db_id_col:    sess_id
      db_data_col:  sess_data
      db_time_col:  sess_time
  
  user:
    param:
      timeout: 1800
  
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name: true

  mailer:
    param:
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host:             mail.gandi.net
          port:             465
          encryption:       ssl
          username:         webmaster@up2green.com
          password:         smartw3bm@il
