user_forgot_password:
  url:   /forgotpwd
  param: { module: user, action: forgotPassword }

sf_guard_signin:
  url: /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_register:
  url:   /register
  param: { module: user, action: inscription }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

change_language:
  url:   /change_language
  param: { module: user, action: changeLanguage }

ajax_more_results:
  url: /ajax/moreresults/*
  param: { module: ajax, action: moreresults, sf_format: xml }

clic_pub:
  url: /ajax/clicPub
  param: { module: ajax, action: clicPub, sf_format: xml }

couponsCSV:
  url:    /exportCoupons
  param:  {module: plantation, action: couponsCSV}

####################
##### LANDING
####################
landing_homepage:
  url: /landing
  param: {module: landing, action: index}
plantation_landing_homepage:
  url: /plantation/landing
  param: {module: landing, action: index}

landing_page_partenaire:
  url: /landing/pagePartenaire/:partenaire/:operation
  param: {module: landing, action: pagePartenaire, partenaire: 0, operation: 0}
plantation_landing_page_partenaire:
  url: /plantation/landing/pagePartenaire/:partenaire/:operation
  param: {module: landing, action: pagePartenaire, partenaire: 0, operation: 0}

landing_map:
  url: /landing/map/:partenaire/:operation
  param: {module: landing, action: map, partenaire: 0, operation: 0}
plantation_landing_map:
  url: /plantation/landing/map/:partenaire/:operation
  param: {module: landing, action: map, partenaire: 0, operation: 0}


landing_plantation:
  url: /landing/plantation/:partenaire/:operation
  param: {module: landing, action: plantation, partenaire: 0, operation: 0}
plantation_landing_plantation:
  url: /plantation/landing/plantation/:partenaire/:operation
  param: {module: landing, action: plantation, partenaire: 0, operation: 0}

landing_partenaire:
  url: /landing/partenaire/:partenaire/:operation
  param: {module: landing, action: partenaire, partenaire: 0, operation: 0}
plantation_landing_partenaire:
  url: /plantation/landing/partenaire/:partenaire/:operation
  param: {module: landing, action: partenaire, partenaire: 0, operation: 0}

####################
##### PLANTATION
####################

plantation:
  url: /plantation
  param: { module: plantation, action: index}

plantation_login:
  url:   /plantation/login
  param: { module: sfGuardAuth, action: signin }

plantation_logout:
  url:   /plantation/logout
  param: { module: sfGuardAuth, action: signout }

plantation_confirmation:
  url: /plantation/confirm
  param: {module: plantation, action: confirm}

plantation_plant:
  url: /plantation/plant
  param: {module: plantation, action: plant}

plantation_change_language:
  url:   /plantation/change_language
  param: { module: user, action: changeLanguage }

####################
##### SEARCH
####################

search:
  url:   /search
  param: { module: recherche, action: search }

####################
##### GALLERY
####################

gallery_show:
  url:   /gallery/:slug
  param: { module: gallery, action: show }

####################
##### GENERAL
####################

general_article:
  url:   /article/:slug
  param: { module: recherche, action: viewElement, type: article }

unsuscribe:
  url:    /newsletter/unsuscribe/:email
  param:  { module: newsletter, action: unsuscribe }

user_profil:
  url:   /user/profil/
  param: { module: user, action: profil }
plantation_user_profil:
  url:   /plantation/user/profil/
  param: { module: user, action: profil }

partenaire_profil:
  url:   /user/partenaireProfil/
  param: { module: user, action: partenaireProfil }
plantation_partenaire_profil:
  url:   /plantation/user/partenaireProfil/
  param: { module: user, action: partenaireProfil }

partenaire_profil_attestation:
  url:   /user/partenaireAttestation/
  param: { module: user, action: partenaireAttestation }
plantation_partenaire_profil_attestation:
  url:   /plantation/user/partenaireAttestation/
  param: { module: user, action: partenaireAttestation }

partenaire_profil_page:
  url:   /user/partenairePage/
  param: { module: user, action: partenairePage }
plantation_partenaire_profil_page:
  url:   /plantation/user/partenairePage/
  param: { module: user, action: partenairePage }

user_filleul:
  url:   /user/filleul/
  param: { module: user, action: listFilleul }
plantation_user_filleul:
  url:   /plantation/user/filleul/
  param: { module: user, action: listFilleul }

user_invite_filleul:
  url:   /user/invitation/
  param: { module: user, action: inviteFilleul }
plantation_user_invite_filleul:
  url:   /plantation/user/invitation/
  param: { module: user, action: inviteFilleul }

user_coupon:
  url:   /user/coupon/
  param: { module: user, action: coupon }
plantation_user_coupon:
  url:   /plantation/user/coupon/
  param: { module: user, action: coupon }

checkout_coupon:
  url:   /checkout/coupon
  param: { module: checkout, action: coupon}
plantation_checkout_coupon:
  url:   /plantation/checkout/coupon
  param: { module: checkout, action: coupon}

checkout_credit:
  url:   /checkout/credit
  param: { module: checkout, action: credit }
plantation_checkout_credit:
  url:   /plantation/checkout/credit
  param: { module: checkout, action: credit }

homepage:
  url: /
  param: { module: recherche, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action
