user_forgot_password:
  url:   /forgotpwd
  param: { module: user, action: forgotPassword }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_register:
  url:   /register
  param: { module: user, action: inscription }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

ajax_more_results:
  url: /ajax/moreresults/*
  param: { module: ajax, action: moreresults, sf_format: xml }


couponsCSV:
  url:    /exportCoupons.csv
  param:  {module: plantation, action: couponsCSV}

couponsUsedCSV:
  url:    /exportCouponsUsed.csv
  param:  {module: plantation, action: couponsUsedCSV}

####################
##### LANDING
####################

landing_plantation:
  url: /landing/plantation/:partenaireOffset
  param: {module: landing, action: plantation, partenaireOffset: 0}

####################
##### BLOG
####################

blog_organisme_list:
  url:   /blog/organisme
  param: { module: blog, action: viewList, type: organisme }

blog_organisme:
  url:   /blog/organisme/:slug
  param: { module: blog, action: viewElement, type: organisme }

blog_article_list:
  url:   /blog/article
  param: { module: blog, action: viewList, type: article }

blog_article:
  url:   /blog/article/:slug
  param: { module: blog, action: viewElement, type: article }

blog_programme_list:
  url:   /blog/programme
  param: { module: blog, action: viewList, type: programme }

blog_programme:
  url:   /blog/programme/:slug
  param: { module: blog, action: viewElement, type: programme }

blog:
  url:   /blog/:articlesOffset/:programmesOffset/:partenairesOffset/:changement
  param: { module: blog, action: index, articlesOffset: 0, programmesOffset: 0, partenairesOffset: 0, changement: 0 }

blog:
  url: /blog
  param: { module: blog, action: index}
  
####################
##### PLANTATION
####################

plantation:
  url: /plantation
  param: { module: plantation, action: index}

plantation_liste_coupon_partenaire:
  url: /plantation/listeCouponsPartenaires
  param: { module: plantation, action: index, view: listeCouponsPartenaires }

plantation_login:
  url:   /plantation/login
  param: { module: sfGuardAuth, action: signin }

plantation_logout:
  url:   /plantation/logout
  param: { module: sfGuardAuth, action: signout }
  
plantation_landing_homepage:
  url: /plantation/landing
  param: {module: landing, action: index}
  
plantation_landing_plantation_homepage:
  url: /plantation/landing/plantation
  param: {module: landing, action: plantation}

plantation_landing_plantation:
  url: /plantation/landing/plantation/:partenaireOffset
  param: {module: landing, action: plantation, partenaireOffset: 0}

homepage:
  url: /
  param: { module: recherche, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
