user_forgot_password:
  url:   /forgotpwd
  param: { module: user, action: forgotPassword }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

ajax_more_results:
  url: /ajax/moreresults/*
  param: { module: ajax, action: moreresults, sf_format: xml }

homepage:
  url:   /
  param: { module: recherche, action: index }

moteur:
  url:   /moteur
  param: { module: recherche, action: index }

plantation:
  url: /plantation
  param: { module: plantation, action: index}

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
