# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Up2green
    description:  Moteur de recherche, plateforme de reforestation et site associatif
    keywords:     up2green, recherche, reforestation, foret, arbre, biodiversite, coupon, carbone, CO2, uptogreen, terre, planète, programme, organisme, plantation en ligne, émission, compensation, collectivité, partenaire, cadeau, vert
    #language:     en
    #robots:       index, follow
    
  stylesheets:    [reset.css, main.css, button.css, module.css, form.css, jquery.gritter.css]

  javascripts:    [jquery-1.4.2.js, main.js, min/jquery.gritter.min.js]

  has_layout:     true
  title: Up2green
  layout:         layout
