# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

dev:
  metas:
    robots:       nofollow, noindex

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Up2green
    description:  Moteur de recherche, plateforme de reforestation et site associatif
    keywords:     up2green, recherche, reforestation, foret, arbre, biodiversite, coupon, carbone, CO2, uptogreen, terre, planète, programme, organisme, plantation en ligne, émission, compensation, collectivité, partenaire, cadeau, vert
    robots:       index, follow
    #language:     en
  stylesheets:
    - "reset.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "main.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "button.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "module.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "form.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "tooltip.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.gritter.css?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "min/jquery-1.4.4.min.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "min/jquery.gritter.min.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.timers.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.dropshadow.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.cookie.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "mbTooltip.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.scrollTo.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "main.js?v=<?php echo sfConfig::get('app_media_version') ?>"
  has_layout: true
  title: Up2green
  layout: layout
