# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Up2green
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    
  stylesheets:    [reset.css, main.css, button.css, module.css, form.css]

  javascripts:    [jquery-1.4.2.js, main.js]

  has_layout:     true
  title: Up2green
  layout:         layout
