inviteFilleulSuccess:
  javascripts:
    - "form.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    
inscriptionSuccess:
  javascripts:
    - "form.js?v=<?php echo sfConfig::get('app_media_version') ?>"