generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Categorie
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          categorie
    with_doctrine_route:   true
    actions_base_class:    sfActions
    config:
      actions: ~
      fields:  
        is_active: {label: Actif ?}
        name: {label: Titre}
        unique_name: {label: Identifiant unique }
        parent_id: {label: Catégorie parente }        
      list:
        title: Liste des catégories
        max_per_page: 15
        display: [is_active, unique_name, name, parent]
        layout:  stacked
        params:  %%is_active%% <small>%%parent%%</small> - %%name%% (<em>%%unique_name%%</em>)
      filter:  ~
      form:    ~
      edit:
        title: Modification de la catégorie "%%name%%" (identifiant : "%%unique_name%%")
      new:
        title: Nouvelle catégorie
