default:
  metas:
    title: "Up2green : Le site Associatif"

all:
  stylesheets:
    - "blog?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "blog?v=<?php echo sfConfig::get('app_media_version') ?>"
  layout: blog