indexSuccess:
  stylesheets:    [blog.css]
  javascripts:    [blog.js]
  layout:         blog

viewElementSuccess:
  stylesheets:    [blog.css]
  javascripts:    [blog.js]
  layout:         blog

viewListSuccess:
  stylesheets:    [blog.css]
  javascripts:    [blog.js]
  layout:         blog

default:
  metas:
    title: Up2green : Le site Associatif
    javascripts:    [blog.js]
