indexSuccess:
  stylesheets:    [blog.css]
  javascripts:    [blog.js]
  layout:         blog

viewElementSuccess:
  stylesheets:    [blog.css]
  javascripts:    [blog.js]
  layout:         blog

viewListSuccess:
  stylesheets:    [blog.css]
  javascripts:    [blog.js]
  layout:         blog
