mapSuccess:
  stylesheets:
    - "plantation.css?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "plantation.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation_planter.js?v=<?php echo sfConfig::get('app_media_version') ?>"

all:
  stylesheets:
    - "plantation.css?v=<?php echo sfConfig::get('app_media_version') ?>"
default:
  metas:
    title: Up2green Reforestation
  layout: landing