generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Lien
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lien
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        display: [Category, rank, =src, is_active]
        sort: [category_id, asc]
      filter:  ~
      form:
        display:
          Default: [category_id, src, is_active, rank]
          Translation: [fr, en]
      edit:    ~
      new:     ~
