generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Lien
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          lien
    with_doctrine_route:   true
    actions_base_class:    sfActions
    config:
      actions: ~
      fields:  
        is_active: {label: Actif ?}
        src: {label: url, help: Partie renseignant l'attribut "href" du lien }
        title: {label: Titre}
      list:
        title: Liste des liens
        max_per_page: 10
        layout:  stacked
        display: [is_active, categories, title, src]
        params:  %%is_active%% [ %%StringCategories%% ] %%title%% (<em>%%src%%</em>)
      filter:  ~
      form:    ~
      edit:
        title: Modification du lien "%%title%%" (catégorie(s) : "%%StringCategories%%")
      new:
        title: Nouveau lien
