# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/fr/13-View

couponsCSVSuccess:
  has_layout: off
  http_metas:
    content-type: application/msexcel
couponsUsedCSVSuccess:
  has_layout: off
  http_metas:
    content-type: application/msexcel

default:
  metas:
    title: "Up2green : La plate-forme de Reforestation"
  layout: plantation
  stylesheets:
    - "reset?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "main?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "button?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "module?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "tooltip?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "min/jquery-1.4.4.min?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "min/jquery-ui-1.8.2.custom.min?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "main?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.scrollTo?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation_planter?v=<?php echo sfConfig::get('app_media_version') ?>"
