# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/fr/13-View

couponsCSVSuccess:
  has_layout: off
  http_metas:
    content-type: application/msexcel
couponsUsedCSVSuccess:
  has_layout: off
  http_metas:
    content-type: application/msexcel


default:
  stylesheets:    [reset.css, main.css, button.css, module.css, plantation.css]
  javascripts:
    - min/jquery-1.4.2.min.js
    - min/jquery-ui-1.8.2.custom.min.js
    - main.js
    - jquery.scrollTo.js
    - plantation.js
    - plantation_planter.js
