couponsCSVSuccess:
  has_layout: off
  http_metas:
    content-type: application/msexcel

all:
  layout: plantation
  stylesheets:
    - "plantation.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery-ui-1.8.1.custom.css?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "min/jquery-ui-1.8.2.custom.min.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation_planter.js?v=<?php echo sfConfig::get('app_media_version') ?>"
  metas:
    title: "Up2green : La plate-forme de Reforestation"