# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/fr/13-View

couponsCSVSuccess:
  has_layout: off
  http_metas:
    content-type: application/msexcel
couponsUsedCSVSuccess:
  has_layout: off
  http_metas:
    content-type: application/msexcel

default:
  metas:
    title: "Up2green : La plate-forme de Reforestation"
  layout: plantation
  stylesheets:
    - "reset.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "main.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "button.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "module.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation.css?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "tooltip.css?v=<?php echo sfConfig::get('app_media_version') ?>"
  javascripts:
    - "min/jquery-1.4.4.min.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "min/jquery-ui-1.8.2.custom.min.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "main.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "jquery.scrollTo.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation.js?v=<?php echo sfConfig::get('app_media_version') ?>"
    - "plantation_planter.js?v=<?php echo sfConfig::get('app_media_version') ?>"
