generator:
  class: sfDoctrineGenerator
  param:
    model_class:           profil
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          profil
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Gestion des profils d'utilisateurs
        display: [id, user, credit, culture, is_newsletter]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
