test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=up2green_test
      username: username
      password: sm@rTp0wereD!pwd

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=up2green
      username: username
      password: sm@rTp0wereD!pwd
