# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  base_search: 10
  more_search: 10
  max_programme_plantation_list: 10
  yahoo_id: %20Kj_TvU_V34EbCKKfZ4yPkczw6EL_AFnECTq9EVUyhMyTGgpSf97RhYE6KHWsPQ--
  google_maps_api:
    keys:
      88.160.179.194: ABQIAAAAOI4H-vEy3CLlbxYWTrlYpxTzS27WZts-8OABpbNREg0l7jdhvxS_F5G6BDQGS2k5eFsNty94e0_K2Q
      dev.smartit.fr: ABQIAAAA2WG-bF-JJB9XacJsjS1oChS9Vzbq_KGPRHYXo4EHeU4bpWZ42hQuCN9qMziWKJaXp6loVe_kWNej7w
  url:
    web: http://boss.yahooapis.com/ysearch/web/v1/
