generator:
  class: sfDoctrineGenerator
  param:
    model_class:           filleul
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          filleul
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id, Parrain, Filleul, email_address]
        title:   Gestion du parainage
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
