article:
  actAs: 
    Timestampable: ~
    I18n:
      fields: [title, accroche, description]
      actAs:
        Sluggable: { fields: [title], uniqueBy: [lang, title] }
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    category_id:
      type: integer(4)
    title:
      type: string(255)
      notnull: true
    accroche:
      type: string(1000)
    description:
      type: clob(65535)
    logo:
      type: string(255)
    is_active:
      type: boolean
      default: 0
    rank:
      type: integer(4)
      notnull: true
      default: 1
  relations:
    Category:
      class: category
      local: category_id
      foreignAlias: Articles

newsletter:
  actAs: 
    Timestampable: ~
    I18n:
      fields: [title, content]
      actAs:
        Sluggable: { fields: [title], uniqueBy: [lang, title] }
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    category_id:
      type: integer(4)
    title:
      type: string(255)
      notnull: true
    content:
      type: clob(65535)
    reply_to:
      type: string(128)
      notnull: true
      default: noreply@up2green.com
    email_from:
      type: string(128)
      notnull: true
      default: newsletter@up2green.com
    is_forced:
      type: boolean
      default: 0
    sent_at:
      type: timestamp
  relations:
    category:
      class: category
      local: category_id
      foreignAlias: Newsletters

lien:
  actAs:
    Timestampable: ~
    I18n:
      fields: [title]
      actAs:
        Sluggable: { fields: [title], uniqueBy: [lang, title] }
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    category_id:
      type: integer(4)
    title:
      type: string(255)
      notnull: true
    src:
      type: string(255)
    is_active:
      type: boolean
      default: 0 
    rank:
      type: integer(4)
      notnull: true
      default: 1
  relations:
    category:
      class: category
      local: category_id
      foreignAlias: Liens
      
category:
  actAs: 
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    unique_name:
      type: string(30)
      unique: true
    rank:
      type: integer(4)
      notnull: true
      default: 1
    is_active:
      type: boolean
      default: 1