point:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    latitude:
      type: decimal
      scale: 6
      notnull: true
    longitude:
      type: decimal
      scale: 6
      notnull: true
    altitude:
      type: decimal
      scale: 6
      notnull: true
      
polygonne:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    unique_name:
      type: string(30)
      unique: true
      notnull: true

polygonnePoint:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    polygonne_id:
      type: integer(4)
      primary: true
    point_id:
      type: integer(4)
      primary: true
  relations:
    polygonne:
      local: polygonne_id
      foreignAlias: Points
      onDelete: CASCADE
    point:
      local: point_id
      foreignAlias: Polygonnes
      onDelete: CASCADE
      
programmePolygonne:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    polygonne_id:
      type: integer(4)
      primary: true
    programme_id:
      type: integer(4)
      primary: true
  relations:
    programme:
      local: programme_id
      foreignAlias: Polygonnes
      onDelete: CASCADE
    polygon:
      local: polygonne_id
      foreignAlias: Programmes
      onDelete: CASCADE