partenaire:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: bigint(20)
      notnull: true
      unique: true
    title:
      type: string(45)
      default: null
    accroche:
      type: clob(65535)
      default: null
    description:
      type: clob(65535)
      default: null
    page:
      type: clob(65535)
      default: null
    attestation:
      type: string(128)
      default: null
    url:
      type: string(150)
      default: null
  relations:
    User:
      class: sfGuardUser
      local: user_id
      onDelete: CASCADE
      foreignType:  one
      foreignAlias: Partenaire
 
partenaireLogo:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    partenaire_id:
      type: integer(4)
      notnull: true
    src:
      type: string(128)
      notnull: true
    href:
      type: string(128)
  relations:
    partenaire:
      local: partenaire_id
      foreignAlias: Logos
      type: one
      onDelete: CASCADE

partenaireProgramme:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    partenaire_id:
      type: integer(4)
      notnull: true
    programme_id:
      type: integer(4)
      notnull: true
    number:
      type: integer
      default: 0
      notnull: true
    hardcode:
      type: integer
      default: 0
      notnull: true
  relations:
    partenaire:
      local: partenaire_id
      foreignAlias: Programmes
      type: one
      onDelete: CASCADE
    programme:
      local: programme_id
      foreignAlias: Partenaires
      onDelete: CASCADE
      type: one
