organisme:
  actAs: 
    Timestampable: ~
    I18n:
      fields: [title, accroche, description]
      actAs:
        Sluggable: { fields: [title], uniqueBy: [lang, title] }
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    url:
      type: string(128)
    title:
      type: string(128)
    accroche:
      type: string(1000)
    description:
      type: clob(65535)
    logo:
      type: string(128)
      default: null
    is_active:
      type: boolean
      default: 1

programme:
  actAs: 
    Timestampable: ~
    I18n:
      fields: [title, accroche, description]
      actAs:
        Sluggable: { fields: [title], uniqueBy: [lang, title] }
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    organisme_id:
      type: integer(4)
      default: null
    title:
      type: string(128)
    accroche:
      type: string(1000)
    description:
      type: clob(65535)
    geoadress:
      type: string(255)
      default: null
    is_active:
      type: boolean
      default: 1
    max_tree:
      type: integer(4)
      notnull: true
    logo:
      type: string(128)
      default: null
  relations:
    Organisme:
      class: organisme
      local: organisme_id
      foreignAlias: Programmes

tree:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    programme_id:
      type: integer(4)
      notnull: true
  relations:
    Programme:
      class: programme
      local: programme_id
      foreignAlias: Trees

treeUser:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    tree_id:
      type: integer(4)
      primary: true
    user_id:
      type: bigint(20)
      primary: true
  relations:
    tree:
      local: tree_id
      foreignType:  one
      foreignAlias: User
      onDelete: CASCADE
    user:
      class: sfGuardUser
      local: user_id
      foreignAlias: Trees
      
partenaire:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: bigint(20)
      notnull: true
      unique: true
    logo:
      type: string(128)
      default: null
    title:
      type: string(45)
      default: null
    accroche:
      type: string(1000)
      default: null
    description:
      type: clob(65535)
      default: null
    url:
      type: string(150)
      default: null
  relations:
    User:
      class: sfGuardUser
      local: user_id
      onDelete: CASCADE
      foreignType:  one
      foreignAlias: Partenaire
      
partenaireProgramme:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    partenaire_id:
      type: integer(4)
      primary: true
    programme_id:
      type: integer(4)
      primary: true
  relations:
    partenaire:
      local: partenaire_id
      foreignAlias: Programmes
      onDelete: CASCADE
    programme:
      local: programme_id
      foreignAlias: Partenaires
      onDelete: CASCADE
