devise:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    unique_name:
      type: string(30)
      unique: true
    conversion:
      type: double(18,10)
      notnull: true

