generator:
  class: sfDoctrineGenerator
  param:
    model_class:           programme
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          programme
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=id, organisme, geoadress, is_active, max_tree]
        object_actions:
          _edit:        ~
          _delete:      ~
          show:        { label: Show Trees, action: showTrees }
      filter:  ~
      form:
        display:
          Default: [organisme_id, is_active, max_tree, add_tree, logo]
          GeoLocalization: [geoadress, Point, polygonnes_list]
          Translation: [fr, en]
      edit:    ~
      new:     ~
