generator:
  class: sfDoctrineGenerator
  param:
    model_class:           programme
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          programme
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=id, organisme, geoadress, is_active, max_tree]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
